### ISSUE TITLE
Create product categories

### ISSUE THREAD

**Issue by denniswitzel** [denniswitzel/capstone-project#1]
## Value statement - a requirement, not a solution
As a **user** 
I want **an overview of product categories** 
so that **I can find products more easliy through an enclosed category** 

## Description (Text, Scribble, Wireframe, Design)
<img width="312" alt="Screenshot 2020-08-28 at 12 02 15" src="https://user-images.githubusercontent.com/67911876/91548860-5c03bf80-e926-11ea-9a96-9356611881a8.png">

## Acceptance criteria
- [x] All necessary categories are listed on the site
- [x] All categories can be clicked
- [x] All categories lead to a new site

## Tasks
- [x] Create feature branch (feat/product-categories)
- [x] Create Category component in Storybook
- [x] Write component tests
- [x] Add components to App

## Complexity
small
