### ISSUE TITLE
Favorites page

### ISSUE THREAD

**Issue by denniswitzel** [denniswitzel/capstone-project#10]
## Value statement - a requirement, not a solution
As a **use** 
I need **a favorite page** 
so that **it is easier to get an overview of all the favored products** 

## Description (Text, Scribble, Wireframe, Design)
<img width="407" alt="Screenshot 2020-09-07 at 09 17 28" src="https://user-images.githubusercontent.com/67911876/92359105-fb753f00-f0ea-11ea-9012-b529ee5e9d7a.png">

## Acceptance criteria
- [ ] Favorites page is accessible on ever page
- [ ] Every favorite is displayed on the page
- [ ] Favorites are sorted alphabetically 

## Tasks
- [ ] Create feature branch
- [ ] Create favorites page in storybook 
- [ ] Create favorites navigation button in storybook 
- [ ] Set route for the favorites navigation button to `/favorites`
- [ ] Load favorites from local storage
- [ ] Display data on favorites page
- [ ] Test the component
- [ ] Implement into app

## Size
medium
