### ISSUE TITLE
Filter products

### ISSUE THREAD

**Issue by denniswitzel** [denniswitzel/capstone-project#14]
## Value statement - a requirement, not a solution
As a **user** 
I want **a feature to filter the products** 
so that **I can hide products that I am allergic to** 

## Description (Text, Scribble, Wireframe, Design)
<img width="372" alt="Screenshot 2020-09-16 at 11 44 24" src="https://user-images.githubusercontent.com/67911876/93320998-037f5e00-f812-11ea-8cad-de8787505eee.png">

## Acceptance criteria
- [ ] Filter show on each product list page
- [ ] Filter contains the allergies "gluten" and "soy"
- [ ] By clicking on one of the allergies all products with these allergies are hidden

## Tasks
- [ ] Create feature branch
- [ ] Add filter icon to product list page
- [ ] Create filter component in storybook
- [ ] Use filter method on products
- [ ] Test the component with unit and integration tests
- [ ] Implement into App

## Size
medium
