### ISSUE TITLE
Rate the products from 1 to 5

### ISSUE THREAD

**Issue by denniswitzel** [denniswitzel/capstone-project#19]
## Value statement - a requirement, not a solution
As a **use** 
I want **to rate a product** 
so that **I can see which products I liked** 

## Description (Text, Scribble, Wireframe, Design)
<img width="300" alt="Screenshot 2020-09-21 at 09 27 13" src="https://user-images.githubusercontent.com/67911876/93741404-a65a2280-fbec-11ea-8f1d-4bcd4768a9f6.png">

## Acceptance criteria
- [ ] The use can select a rating from 1 to 5
- [ ] After submitting the rating the user can change the rating
- [ ] After a reopen or reload of the app the rating appears as set by the user
- [ ] After a reopen or reload of the app the rating appears as set by the user

## Tasks
- [ ] Create feature branch
- [ ] Build component with storybook
- [ ] Connect to backend
- [ ] Send POST request to backend after submitting the rating
- [ ] Test the component
- [ ] Implement into build

## Size
medium
