### ISSUE TITLE
Overview of vegan products

### ISSUE THREAD

**Issue by denniswitzel** [denniswitzel/capstone-project#2]
## Value statement - a requirement, not a solution
As a **user** 
I need **a list** 
so that **I see all the vegan meat replacement products** 

## Description (Text, Scribble, Wireframe, Design)
<img width="310" alt="Screenshot 2020-08-27 at 12 04 55" src="https://user-images.githubusercontent.com/67911876/91534232-7b442200-e911-11ea-9c0c-1b1ffa9f673f.png">

## Acceptance criteria
- [x] All products are listed
- [x] Every product has a name and a picture
- [x] Products are divided into categories
- [x] Categories are sorted alphabetically

## Tasks
- [x] Create feature branch
- [x] Setup JSON files for each product category
- [x] Create Product component in Storybook
- [x] Product component tests
- [x] Add Product component to the App
- [x] Optimize styling 

## Complexity
medium
