### ISSUE TITLE
New page for highest rated products

### ISSUE THREAD

**Issue by denniswitzel** [denniswitzel/capstone-project#20]
## Value statement - a requirement, not a solution
As a **user** 
I need **an overview of the highest rated products** 
so that **I can see what other people liked** 

## Description (Text, Scribble, Wireframe, Design)
<img width="300" alt="Screenshot 2020-09-21 at 09 36 27" src="https://user-images.githubusercontent.com/67911876/93742157-ef5ea680-fbed-11ea-9d96-11bacf3ad884.png">

## Acceptance criteria
- [ ] A new page is accessible over the navigation
- [ ] On this page the best 20 products from all categories are being listed in descending order
- [ ] The rating is displayed under each product
- [ ] Clicking on the product leads to the detail page

## Tasks
- [ ] Create feature branch
- [ ] Create component and implement into storybook
- [ ] GET request to backend to get the rating of the product
- [ ] Every rating for each product must be reduced to one number
- [ ] Sort the products from highest to lowest rating
- [ ] Test the component and the implementation of the GET requests
- [ ] Implement into live app

## Size
medium
