### ISSUE TITLE
Link the categories with products

### ISSUE THREAD

**Issue by denniswitzel** [denniswitzel/capstone-project#3]
## Value statement - a requirement, not a solution
As a **user** 
I want **to click on a category** 
so that **I see all the products connected to the category** 

## Description (Text, Scribble, Wireframe, Design)
<img width="613" alt="Screenshot 2020-08-28 at 12 09 02" src="https://user-images.githubusercontent.com/67911876/91549475-4b077e00-e927-11ea-8935-5910d16e3914.png">

## Acceptance criteria
- [x] Clicking on a category leads the user to the associated products
- [x] Each category is added to the root URL e.g. `/burgers`
- [x] Headline states the name of the category
- [x] Arrow let's you return to the category page

## Tasks
- [x] Create router for every category
- [x] Update existing component in Storybook
- [x] Test the updated component
- [x] Add component to the app

## Complexity
medium
