### ISSUE TITLE
Sort products

### ISSUE THREAD

**Issue by denniswitzel** [denniswitzel/capstone-project#4]
## Value statement - a requirement, not a solution
As a **user** 
I need **an alphabetically sorted list** 
so that **it is easier to find products** 

## Description (Text, Scribble, Wireframe, Design)
<img width="416" alt="Screenshot 2020-08-28 at 12 25 00" src="https://user-images.githubusercontent.com/67911876/91550931-a2a6e900-e929-11ea-8fff-3326403302f7.png">

## Acceptance criteria
- [x] Products are sorted alphabetically

## Tasks
- [x] Use sort function to achieve the desired outcome
- [x] Implement into app

## Size
small
