### ISSUE TITLE
Product detail page

### ISSUE THREAD

**Issue by denniswitzel** [denniswitzel/capstone-project#8]
## Value statement - a requirement, not a solution
As a **user** 
I need **a detailed page for the products** 
so that **I can see ingredients and allergies of a specific product** 

## Description (Text, Scribble, Wireframe, Design)
<img width="390" alt="Screenshot 2020-09-07 at 08 51 54" src="https://user-images.githubusercontent.com/67911876/92357050-79cfe200-f0e7-11ea-98e8-1892c067514d.png">

## Acceptance criteria
- [ ] Every product can be clicked an leads to a new page with detailed information
- [ ] Product name, image, ingredients and allergies are listed on that page
- [ ] "Back"-Arrow to return to the previous page

## Tasks
- [ ] Create feature branch
- [ ] Set routes for each product
- [ ] Display all information from the arrays containing the product information
- [ ] Create component in storybook
- [ ] Test the component
- [ ] Implement into App

## Size
medium
