### ISSUE TITLE
Favor products

### ISSUE THREAD

**Issue by denniswitzel** [denniswitzel/capstone-project#9]
## Value statement - a requirement, not a solution
As a **user** 
I want **to set a product as favorit** 
so that **I see which products I liked or want to try in the future** 

## Description (Text, Scribble, Wireframe, Design)
<img width="404" alt="Screenshot 2020-09-07 at 09 00 10" src="https://user-images.githubusercontent.com/67911876/92359293-51e27d80-f0eb-11ea-9bfe-0720ccbbab75.png">

## Acceptance criteria
- [ ] Click on the heart to favor the product
- [ ] Favorite stays active after reload
- [ ] Favorite styling is different when active

## Tasks
- [ ] Create feature branch
- [ ] Create component in storybook
- [ ] Save the product that is favored in local storage
- [ ] Test the component
- [ ] Implement into running app

## Size
small
